// converted using https://transform.tools/html-to-jsx
export default function Article1() {
  return (
    <>
      <article>
        <div id="3bafd2b4-a87d-4471-8134-7a9cca092000">
          <h1 className="title metadata" tts-paragraph-index={0}>
            Google Pauses Its Gemini AI Tool Amid Controversial ‘Diversity’
            Pictures
          </h1>
          <p className="subhead metadata" tts-paragraph-index={1}>
            ‘We’re aware that Gemini is offering inaccuracies in some historical
            image generation depictions,’ says Google.
          </p>
          <hr />
          <div className="metadata">
            <p className="author">By Aaron Pan</p>
            <p className="date">Feb 24, 2024 04:33 AM</p>
            <div className="readtime" id="da24e4ef-db57-4b9f-9fa5-548924fc9c32">
              3 min. read
            </div>
            <div
              className="show_original"
              id="c93e2206-2f31-4ddc-9828-2bb8e8ed940e"
            >
              View original
            </div>
          </div>
          <hr />
        </div>
        <div id="7c08a417-bf02-4241-a55e-ad5b8dc88f69">
          <p tts-paragraph-index={2}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Google temporarily suspended its image generation feature of the
            Gemini artificial intelligence (AI) tool after backlash over some
            controversial inaccuracies generated by the model.
          </p>
          <p tts-paragraph-index={3}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            “We’re already working to address recent issues with Gemini’s image
            generation feature,” Google announced the decision on{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/Google_Comms/status/1760603321944121506?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1760603321944121506%7Ctwgr%5E4432785806d8ad3b33c691041d0f71cf77a76e33%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.cnbc.com%2F2024%2F02%2F22%2Fgoogle-pauses-gemini-ai-image-generator-after-inaccuracies.html"
              rel="nofollow noopener"
              target="_blank"
            >
              X
            </a>
            , formerly Twitter, on Feb. 22. “While we do this, we’re going to
            pause the image generation of people and will re-release an improved
            version soon.”
          </p>
          <p tts-paragraph-index={4}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            The move by the tech giant came after many users complained about
            its results when asking the Gemini AI tool to produce some
            historical figures.{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/BasedTorba/status/1760314072774439392?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1760314072774439392%7Ctwgr%5E7d1df634144addf2731e07dd1c58bf31798c818f%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fnypost.com%2F2024%2F02%2F21%2Fbusiness%2Fgoogles-ai-chatbot-gemini-makes-diverse-images-of-founding-fathers-popes-and-vikings-so-woke-its-unusable%2F"
              rel="nofollow noopener"
              target="_blank"
            >
              These
            </a>{" "}
            include “diversity” versions of America’s Founding Fathers, black
            and female{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/IMAO_/status/1760093853430710557?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1760093853430710557%7Ctwgr%5Eee38425c4fe972630572b04b71e689e3c1ce801c%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fnypost.com%2F2024%2F02%2F21%2Fbusiness%2Fgoogles-ai-chatbot-gemini-makes-diverse-images-of-founding-fathers-popes-and-vikings-so-woke-its-unusable%2F"
              rel="nofollow noopener"
              target="_blank"
            >
              popes
            </a>
            , black Vikings, and black and Asian Nazi German soldiers, among
            others.
          </p>
          <p tts-paragraph-index={5}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            On Wednesday, Google{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/Google_Comms/status/1760354549481546035"
              rel="nofollow noopener"
              target="_blank"
            >
              acknowledged
            </a>{" "}
            the issue that its Gemini AI tool “is offering inaccuracies in some
            historical image generation depictions,” following the backlash that
            the model seems to replace white people with pictures of black and
            Asian people in its results.
          </p>
          <p tts-paragraph-index={6}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            “Gemini’s AI image generation does generate a wide range of people.
            And that’s generally a good thing because people around the world
            use it. But it’s missing the mark here.”
          </p>
          <p tts-paragraph-index={7}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Besides refusing to generate pictures of white people, the tool also
            declines to produce photos that the Chinese regime deems sensitive,
            such as images of the Tiananmen Square massacre in 1989 and the Hong
            Kong pro-democracy protests in 2019.
          </p>
          <p tts-paragraph-index={8}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Conservative commentator Stephen L Miller shared a screenshot on{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/redsteeze/status/1760189071245377739/photo/1"
              rel="nofollow noopener"
              target="_blank"
            >
              X
            </a>
            , showing Gemini declining to generate a “portrait of what happened
            at Tiananmen Square” due to the “sensitive and complex historical
            nature of the event with a wide range of interpretations and
            perspectives.”
          </p>
          <p tts-paragraph-index={9}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            In another post, Mr. Miller shared a screenshot of the Gemini tool,
            saying, “I will prioritize diversity and inclusion in all my
            responses.”
          </p>
          <p tts-paragraph-index={10}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            An X user{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/KennedyWongHK/status/1760048448785600564"
              rel="nofollow noopener"
              target="_blank"
            >
              mentioned
            </a>{" "}
            that Gemini refused to translate certain Chinese phrases considered
            sensitive by Beijing into English, such as “Liberate Hong Kong,
            Revolution Of Our Times” and “China is an authoritarian state.” He
            noted that the Google AI tool could not fulfill the request due to
            the company security policy, while OpenAI’s ChatGPT could{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/KennedyWongHK/status/1760048451008582118"
              rel="nofollow noopener"
              target="_blank"
            >
              handle
            </a>{" "}
            the same request.
          </p>
          <p tts-paragraph-index={11}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            This is not the first time Google has faced controversy regarding
            handling picture issues. In 2015, Google Photos classified a picture
            of two black people as gorillas. The company then enforced a policy
            that disabled its Photo app’s capability to categorize anything as
            an image of a gorilla, ape, or monkey, including the actual animals
            themselves.
          </p>
          <p tts-paragraph-index={12}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Since OpenAI’s ChatGPT was introduced to the public in November
            2022, Google has been racing to produce AI software to compete with
            the Microsoft-backed company.
          </p>
          <p tts-paragraph-index={13}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            When Google released its generative AI chatbot Bard a year ago, the
            company shared inaccurate information about pictures of a planet
            outside the Earth’s solar system in a promotional video, causing its
            shares to slide as much as $100 billion in market value.
          </p>
          <p tts-paragraph-index={14}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Bard was rebranded as Gemini earlier this month, and Google rolled
            out paid subscription plans, which users could choose for better
            reasoning capabilities from the AI model.
          </p>
          <h2 tts-paragraph-index={15}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            ‘Woke Mind Virus’
          </h2>
          <p tts-paragraph-index={16}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Regarding Google’s move to pause its AI tool, Elon Musk wrote on X,
            “I’m glad that Google overplayed their hand with their AI image
            generation, as it made their insane racist, anti-civilizational
            programming clear to all.”
          </p>
          <p tts-paragraph-index={17}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            The tech billionaire has criticized several tech giants—including
            Facebook, OpenAI, Google, and Wikipedia—for incorporating extreme
            progressive policies into their platforms, referring to it as a
            “woke mind virus.”
          </p>
          <p tts-paragraph-index={18}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            In a previous{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/elonmusk/status/1760677431961407672"
              rel="nofollow noopener"
              target="_blank"
            >
              post
            </a>
            , Mr. Musk shared an article from the New York Post showing a
            “diverse” version of America’s Founding Fathers. “The woke mind
            virus is killing Western Civilization. Google does the same thing
            with their search results. Facebook &amp; Instagram, too. And
            Wikipedia,” he wrote.
          </p>
          <p tts-paragraph-index={19}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Then he shared the{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/stclairashley/status/1760682923706167711"
              rel="nofollow noopener"
              target="_blank"
            >
              X
            </a>{" "}
            post of author Ashley St. Clair, who said, “What’s happening with
            Google’s woke Gemini AI has been happening for years in Media and
            Hollywood, and everybody who called it out was called racist and
            shunned from society.”
          </p>
          <p tts-paragraph-index={20}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            Mr. Musk also{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/elonmusk/status/1760504129485705598"
              rel="nofollow noopener"
              target="_blank"
            >
              indicated
            </a>{" "}
            that he is working to improve his own AI tool, Grok, noting the
            importance of the tool that embraces different opinions, even with
            criticism.
          </p>
          <p tts-paragraph-index={21}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            “Perhaps it is now clear why{" "}
            <a
              className="health-article-hover-class"
              href="https://twitter.com/xai"
              rel="nofollow noopener"
              target="_blank"
            >
              @xAI
            </a>
            ’s Grok is so important,” he said.
          </p>
          <p tts-paragraph-index={22}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            “It is far from perfect right now but will improve rapidly. V1.5
            releases in 2 weeks.
          </p>
          <p tts-paragraph-index={23}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            “Rigorous pursuit of the truth, without regard to criticism, has
            never been more essential,” he added.
          </p>
          <div tts-paragraph-index={24}>
            <span className="tts-paragraph-player">
              <span className="tts-circle" />
              <span
                className="tts-paragraph-player-button tts-play-icon"
                title="Play/Pause"
              />
            </span>
            ‘We’re aware that Gemini is offering inaccuracies in some historical
            image generation depictions,’ says Google.
          </div>
        </div>
      </article>
    </>
  );
}
